#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    if ! getent passwd vast >/dev/null; then
        adduser \
            --system --group --no-create-home --home /var/lib/vast/db \
            vast
    fi
    if ! dpkg-statoverride --list /var/lib/vast/db >/dev/null 2>&1; then
        dpkg-statoverride \
            --quiet --update \
            --add vast vast 0750 /var/lib/vast/db
    fi
    if ! dpkg-statoverride --list /var/log/vast >/dev/null 2>&1; then
        dpkg-statoverride \
            --quiet --update \
            --add vast vast 0750 /var/log/vast
    fi
fi

#DEBHELPER#
